### ISSUE TITLE
Demo link doesn't work

### ISSUE THREAD

**Issue by oliver** [Glowman554/NextOS#6]
Hi, the link to the demo in the README.md file (which goes to https://glowman554.github.io/NextOS/?profile=custom&cdrom.url=https://glowman554.github.io/NextOS/cdrom.iso) does not work for me

This link works fine, though: https://glowman554.gq/NextOS/?profile=custom&cdrom.url=https://glowman554.gq/NextOS/cdrom.iso . I.e. I had to change the ISO URL to glowman554.gq to avoid a CORS error.

**Comment by Glowman554** [comment]
Sorry for the inconvenience, this happend since github pages redirects to the custom url. I didnt yet have this custom url at the time i made the demo thing.

**Comment by oliver** [comment]
Nice, thanks for the quick solution!
